// Objective-C API for talking to github.com/nknorg/eth-resolver-go Go package.
//   gobind -lang=objc github.com/nknorg/eth-resolver-go
//
// File is generated by gobind. Do not edit.

#ifndef __Ethresolver_H__
#define __Ethresolver_H__

@import Foundation;
#include "ref.h"
#include "Universe.objc.h"


@class EthresolverConfig;
@class EthresolverResolver;

@interface EthresolverConfig : NSObject <goSeqRefInterface> {
}
@property(strong, readonly) _Nonnull id _ref;

- (nonnull instancetype)initWithRef:(_Nonnull id)ref;
- (nonnull instancetype)init;
@property (nonatomic) NSString* _Nonnull prefix;
@property (nonatomic) NSString* _Nonnull rpcServer;
@property (nonatomic) NSString* _Nonnull contractAddress;
// skipped field Config.CacheTimeout with unsupported type: time.Duration

@property (nonatomic) long dialTimeout;
@end

@interface EthresolverResolver : NSObject <goSeqRefInterface> {
}
@property(strong, readonly) _Nonnull id _ref;

- (nonnull instancetype)initWithRef:(_Nonnull id)ref;
- (nullable instancetype)init:(EthresolverConfig* _Nullable)config;
- (NSString* _Nonnull)resolve:(NSString* _Nullable)address error:(NSError* _Nullable* _Nullable)error;
@end

FOUNDATION_EXPORT NSString* _Nonnull const EthresolverCONTRACT_ADDRESS;
FOUNDATION_EXPORT NSString* _Nonnull const EthresolverPREFIX;
FOUNDATION_EXPORT NSString* _Nonnull const EthresolverRPC_SERVER;

@interface Ethresolver : NSObject
// skipped variable DefaultConfig with unsupported type: github.com/nknorg/eth-resolver-go.Config

@end

FOUNDATION_EXPORT EthresolverConfig* _Nullable EthresolverGetDefaultConfig(void);

FOUNDATION_EXPORT EthresolverConfig* _Nullable EthresolverMergeConfig(EthresolverConfig* _Nullable config, NSError* _Nullable* _Nullable error);

FOUNDATION_EXPORT EthresolverResolver* _Nullable EthresolverNewResolver(EthresolverConfig* _Nullable config, NSError* _Nullable* _Nullable error);

#endif
