
// Objective-C API for talking to the following Go packages
//
//	nkngolib
//	nkngolib/crypto
//	github.com/nknorg/nkn-sdk-go
//	github.com/nknorg/ncp-go
//	github.com/nknorg/nkn/v2/transaction
//	github.com/nknorg/nkngomobile
//	github.com/nknorg/eth-resolver-go
//	github.com/nknorg/dns-resolver-go
//
// File is generated by gomobile bind. Do not edit.
#ifndef __Nkn_FRAMEWORK_H__
#define __Nkn_FRAMEWORK_H__

#include "Nkngolib.objc.h"
#include "Crypto.objc.h"
#include "Nkn.objc.h"
#include "Ncp.objc.h"
#include "Transaction.objc.h"
#include "Nkngomobile.objc.h"
#include "Ethresolver.objc.h"
#include "Dnsresolver.objc.h"
#include "Universe.objc.h"

#endif
